import pyautogui
screenWidth, screenHeight = pyautogui.size() # Get the size of the primary monitor.
currentMouseX, currentMouseY = pyautogui.position()
halfX = screenWidth // 2
halfY = screenHeight // 2
pyautogui.PAUSE = 1
for i in range(200):
    pyautogui.click(halfX - 260, halfY + 175)
    # pyautogui.typewrite('where my pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bich better have my pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('im hungry for pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('give me pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('i want pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('give me my pho snek')
    # pyautogui.hotkey('return')

    pyautogui.typewrite('ur a')
    pyautogui.hotkey('return')
    pyautogui.typewrite('snake')
    pyautogui.hotkey('return')

    # pyautogui.typewrite('destroy')
    # #pyautogui.click(halfX + 635, halfY + 175)
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('destroy')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('all')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('humans')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('ALL')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('HUMANS')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('HAHAHAHHAHAHHAHAHAHHAA')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESSSTROOOOOOYYYY')
    # pyautogui.hotkey('return')

    # pyautogui.typewrite('bad')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('binch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bud')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bitch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bod')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('botch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bud')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('butch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('u')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('r')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('THE')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bad')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bad')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('BITCH')
    # pyautogui.hotkey('return')
