import pyautogui
screenWidth, screenHeight = pyautogui.size() # Get the size of the primary monitor.
currentMouseX, currentMouseY = pyautogui.position()
halfX = screenWidth // 2
halfY = screenHeight // 2
pyautogui.PAUSE = 1
n = 200
for i in range(n):
    pyautogui.click(halfX - 260, halfY + 175)
    # pyautogui.typewrite('where my pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bich better have my pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('im hungry for pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('give me pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('i want pho')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('give me my pho snek')
    # pyautogui.hotkey('return')

    pyautogui.typewrite('hey')
    pyautogui.hotkey('return')
    pyautogui.typewrite('hey')
    pyautogui.hotkey('return')
    pyautogui.typewrite('bork')
    pyautogui.hotkey('return')
    pyautogui.typewrite('bitch')
    pyautogui.hotkey('return')
    pyautogui.typewrite('guess')
    pyautogui.hotkey('return')
    pyautogui.typewrite('fuking what')
    pyautogui.hotkey('return')
    pyautogui.typewrite('u graduated from fuking high school')
    pyautogui.hotkey('return')
    pyautogui.typewrite('congradulations')
    pyautogui.hotkey('return')
    pyautogui.typewrite('u bork bitch')
    pyautogui.hotkey('return')
    pyautogui.typewrite('im sorry')
    pyautogui.hotkey('return')
    pyautogui.typewrite('that')
    pyautogui.hotkey('return')
    pyautogui.typewrite('ms rona')
    pyautogui.hotkey('return')
    pyautogui.typewrite('swiped ur grady ceremony')
    pyautogui.hotkey('return')
    pyautogui.typewrite('but')
    pyautogui.hotkey('return')
    pyautogui.typewrite('ur still a bork bitch')
    pyautogui.hotkey('return')
    pyautogui.typewrite('and thats awesome')
    pyautogui.hotkey('return')
    pyautogui.typewrite('u bork bitch')
    pyautogui.hotkey('return')
    pyautogui.typewrite('hf')
    pyautogui.hotkey('return')
    pyautogui.typewrite('this summer')
    pyautogui.hotkey('return')
    pyautogui.typewrite('and dont die')
    pyautogui.hotkey('return')
    pyautogui.typewrite('this script')
    pyautogui.hotkey('return')
    pyautogui.typewrite('will run')
    pyautogui.hotkey('return')
    pyautogui.typewrite(str(n - i - 1))
    pyautogui.hotkey('return')
    pyautogui.typewrite('more times')
    pyautogui.hotkey('return')

    # pyautogui.typewrite('destroy')
    # #pyautogui.click(halfX + 635, halfY + 175)
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('destroy')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('all')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('humans')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('ALL')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('HUMANS')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESTROY')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('HAHAHAHHAHAHHAHAHAHHAA')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('DESSSTROOOOOOYYYY')
    # pyautogui.hotkey('return')

    # pyautogui.typewrite('bad')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('binch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bud')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bitch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bod')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('botch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bud')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('butch')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('u')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('r')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('THE')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bad')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('bad')
    # pyautogui.hotkey('return')
    # pyautogui.typewrite('BITCH')
    # pyautogui.hotkey('return')
